version: 2.1
jobs:
  create_infrastructure:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Ensure backed infrastructure exist
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name my-stack22
                
workflows:
  my_workflow:
    jobs:
        -create_infrastructure
  
